### PR TITLE
Update Readme and provide example for devcontainer.json

### PR DESCRIPTION
**Pull request by nichtraunzer**
Update Readme and provide example for devcontainer.json

### CODE REVIEW

**Comment by tbugfinder** [comment]
No cert hack here?

**Comment by nichtraunzer** [comment]
the CERTs are an internal issue only ... i guess nobody else in the world has that problem :)

**Comment by tbugfinder** [comment]
You 'll always end up with an additional guide or repo, though.

**Comment by nichtraunzer** [comment]
> You 'll always end up with an additional guide or repo, though.

tell me the story of my current life 😄

**Pull request merged**
